### ISSUE TITLE
Checkpoint broken

### ISSUE THREAD

**Issue by CSerxy** [feyzaakyurek/rl4f#1]
Hi rl4f authors, 

Thanks for publicizing your excellent work!

I found after downloading this file https://drive.google.com/drive/folders/1lyYe5Aaw2aqpF1witIp7BXuNmRX6LHDm it hints me that "Unable to expend model.tar into alphabetization (Error -1 No such process)"

Would it be possible for you to check and update this checkpoint? Many thanks!

**Comment by feyzaakyurek** [comment]
Hi @CSerxy,

Sorry for the delay in responding. I am glad to hear that you found our work interesting!

I've uploaded the uncompressed pytorch.bin and config files, those hopefully should load correctly.
