### ISSUE TITLE
parallel support

### ISSUE THREAD

**Issue by CSerxy** [feyzaakyurek/rl4f#2]
Hi rl4f authors,

I have a follow-up question regarding your support for tuning recent llm such as vicuna. Those models usually requires 8xA100 gpu support. I wonder if your codebase has parallel training part that could do this (e.g., using the way of "torchrun --nproc_per_node=8 --master_port=20001 demo.py" and setting model's device somehow).

**Comment by feyzaakyurek** [comment]
Hi @CSerxy,

You may want to check out the `apply_model_parallel` argument for `alg` config here: https://github.com/feyzaakyurek/rl4f/blob/master/scripts/training/task_configs/alphabetize/t5large_ppo_on_supervised.yaml#L56C1-L56C1

You can also refer to the original RL4LMs repo for more information.
